export const ipaData = {
  monophthongs: [
    { symbol: "i:", word: "sleep", type: "monophthong" },
    { symbol: "ɪ", word: "slip", type: "monophthong" },
    { symbol: "ʊ", word: "good", type: "monophthong" },
    { symbol: "u:", word: "food", type: "monophthong" },
    { symbol: "e", word: "bed", type: "monophthong" },
    { symbol: "ə", word: "teacher", type: "monophthong" },
    { symbol: "ɜ:", word: "bird", type: "monophthong" },
    { symbol: "ɔ:", word: "door", type: "monophthong" },
    { symbol: "æ", word: "cat", type: "monophthong" },
    { symbol: "ʌ", word: "up", type: "monophthong" },
    { symbol: "ɑ:", word: "far", type: "monophthong" },
    { symbol: "ɒ", word: "on", type: "monophthong" },
  ],
  diphthongs: [
    { symbol: "ɪə", word: "here", type: "diphthong" },
    { symbol: "eɪ", word: "wait", type: "diphthong" },
    { symbol: "ʊə", word: "tourist", type: "diphthong" },
    { symbol: "ɔɪ", word: "boy", type: "diphthong" },
    { symbol: "əʊ", word: "show", type: "diphthong" },
    { symbol: "eə", word: "hair", type: "diphthong" },
    { symbol: "aɪ", word: "my", type: "diphthong" },
    { symbol: "aʊ", word: "cow", type: "diphthong" },
  ],
  consonants: [
    { symbol: "p", word: "pea", type: "consonant", voiced: false },
    { symbol: "b", word: "boat", type: "consonant", voiced: true },
    { symbol: "t", word: "tea", type: "consonant", voiced: false },
    { symbol: "d", word: "dog", type: "consonant", voiced: true },
    { symbol: "ʧ", word: "cheese", type: "consonant", voiced: false },
    { symbol: "ʤ", word: "june", type: "consonant", voiced: true },
    { symbol: "k", word: "car", type: "consonant", voiced: false },
    { symbol: "g", word: "go", type: "consonant", voiced: true },
    { symbol: "f", word: "fly", type: "consonant", voiced: false },
    { symbol: "v", word: "video", type: "consonant", voiced: true },
    { symbol: "θ", word: "think", type: "consonant", voiced: false },
    { symbol: "ð", word: "this", type: "consonant", voiced: true },
    { symbol: "s", word: "see", type: "consonant", voiced: false },
    { symbol: "z", word: "zoo", type: "consonant", voiced: true },
    { symbol: "ʃ", word: "shall", type: "consonant", voiced: false },
    { symbol: "ʒ", word: "television", type: "consonant", voiced: true },
    { symbol: "m", word: "man", type: "consonant", voiced: true },
    { symbol: "n", word: "now", type: "consonant", voiced: true },
    { symbol: "ŋ", word: "sing", type: "consonant", voiced: true },
    { symbol: "h", word: "hat", type: "consonant", voiced: false },
    { symbol: "l", word: "love", type: "consonant", voiced: true },
    { symbol: "r", word: "red", type: "consonant", voiced: true },
    { symbol: "w", word: "wet", type: "consonant", voiced: true },
    { symbol: "j", word: "yes", type: "consonant", voiced: true },
  ]
};
