-- AlterTable
ALTER TABLE "results" ALTER COLUMN "totalScore" SET DATA TYPE DOUBLE PRECISION,
ALTER COLUMN "speakingScore" SET DATA TYPE DOUBLE PRECISION,
ALTER COLUMN "writingScore" SET DATA TYPE DOUBLE PRECISION;
