"""
=============================================================================
  Writing Grading Validation Demo
  IELTS Master English AI -- Thesis Defense
=============================================================================

Analyzes REAL grading results from the Gemini 2.5 Flash experiment.

WORKFLOW (2 steps):
  Step 1: python run_experiment.py   <- calls REAL Gemini API, saves results
  Step 2: python run_demo.py         <- analyzes results, generates charts

DATA:
  - 30 IELTS Task 2 essays with human expert scores
    (source: chillies/IELTS-writing-task-2-evaluation)
  - Each essay graded by Gemini 2.5 Flash via backend-ai/grade_writing()
  - Results file: grading_results.json (generated by run_experiment.py)

RUN:
    pip install numpy scipy scikit-learn matplotlib seaborn pandas
    python run_experiment.py    # Step 1: grade essays via Gemini API
    python run_demo.py          # Step 2: analyze + generate charts
=============================================================================
"""

import os
import json
import numpy as np
from scipy import stats
from sklearn.metrics import cohen_kappa_score
import matplotlib
matplotlib.use('Agg')
import matplotlib.pyplot as plt
import seaborn as sns
import pandas as pd


def load_results():
    """
    Load grading results produced by run_experiment.py (real Gemini API calls).
    """
    script_dir = os.path.dirname(os.path.abspath(__file__))
    local_path = os.path.join(script_dir, "grading_results.json")

    if not os.path.exists(local_path):
        raise FileNotFoundError(
            f"Cannot find grading_results.json.\n"
            f"  Expected at: {local_path}\n"
            f"  Please run: python run_experiment.py  (to grade essays via Gemini API first)"
        )

    with open(local_path, "r", encoding="utf-8") as f:
        results = json.load(f)

    print(f"  Loaded {len(results)} essays from: {local_path}")
    return results


def main():
    script_dir = os.path.dirname(os.path.abspath(__file__))
    charts_dir = os.path.join(script_dir, "charts")
    os.makedirs(charts_dir, exist_ok=True)

    print("=" * 80)
    print("  WRITING GRADING VALIDATION -- LIVE DEMO")
    print("  Real data: Gemini 2.5 Flash via backend-ai/grade_writing()")
    print("=" * 80)

    # ---- Load REAL results from production experiment ----
    results = load_results()

    # ---- Extract scores ----
    human_overall = [r["human"]["overall"] for r in results]
    llm_overall = [r["llm"]["overall"] for r in results]

    # ---- Per-essay comparison table ----
    print(f"\n  {'Essay ID':<12} {'Human':>6} {'LLM':>6} {'Diff':>6}  {'Match'}")
    print(f"  {'-' * 45}")
    for r in results:
        h = r["human"]["overall"]
        l = r["llm"]["overall"]
        diff = l - h
        match = "OK" if abs(diff) <= 0.5 else "MISS"
        symbol = "v" if match == "OK" else "X"
        print(f"  {r['id']:<12} {h:>6.1f} {l:>6.1f} {diff:>+5.1f}  {symbol}")

    # =====================================================================
    # STATISTICAL ANALYSIS
    # =====================================================================
    print(f"\n{'=' * 80}")
    print("  STATISTICAL RESULTS")
    print(f"{'=' * 80}")

    # 1. Pearson correlation
    pearson_r, pearson_p = stats.pearsonr(human_overall, llm_overall)
    print(f"  Pearson r            = {pearson_r:.3f}  (p = {pearson_p:.2e})")

    # 2. Spearman rank correlation
    spearman_rho, spearman_p = stats.spearmanr(human_overall, llm_overall)
    print(f"  Spearman rho         = {spearman_rho:.3f}  (p = {spearman_p:.2e})")

    # 3. Cohen's Kappa (quadratic weighted)
    kappa = cohen_kappa_score(
        [int(x * 10) for x in human_overall],
        [int(x * 10) for x in llm_overall],
        weights="quadratic"
    )
    print(f"  Cohen's Kappa (QWK)  = {kappa:.3f}")

    # 4. Mean Absolute Error
    mae = np.mean(np.abs(np.array(human_overall) - np.array(llm_overall)))
    print(f"  Mean Absolute Error  = {mae:.2f} bands")

    # 5. Agreement rates
    exact = sum(1 for h, l in zip(human_overall, llm_overall) if h == l)
    within_half = sum(1 for h, l in zip(human_overall, llm_overall) if abs(h - l) <= 0.5)
    n = len(results)
    print(f"  Exact match          = {exact}/{n} ({exact / n * 100:.1f}%)")
    print(f"  Within +/-0.5 band   = {within_half}/{n} ({within_half / n * 100:.1f}%)")

    # 6. Bias
    mean_h = np.mean(human_overall)
    mean_l = np.mean(llm_overall)
    bias = mean_l - mean_h
    direction = "(LLM grades higher)" if bias > 0 else "(LLM grades lower)"
    print(f"  Mean Human           = {mean_h:.2f}")
    print(f"  Mean LLM             = {mean_l:.2f}")
    print(f"  Bias (LLM - Human)   = {bias:+.2f} {direction}")

    # ---- Per-criterion analysis ----
    criteria = ["task_achievement", "coherence_cohesion",
                "lexical_resource", "grammatical_range"]
    criteria_display = ["Task Achievement", "Coherence & Cohesion",
                        "Lexical Resource", "Grammatical Range"]

    print(f"\n  --- Per-Criterion Correlation ---")
    print(f"  {'Criterion':<25} {'Pearson':>8} {'Spearman':>9} {'Kappa':>7}")
    print(f"  {'-' * 50}")
    criterion_data = []
    for c, name in zip(criteria, criteria_display):
        h = [r["human"][c] for r in results]
        l = [r["llm"][c] for r in results]
        pr, _ = stats.pearsonr(h, l)
        sr, _ = stats.spearmanr(h, l)
        k = cohen_kappa_score([int(x * 10) for x in h],
                              [int(x * 10) for x in l], weights="quadratic")
        criterion_data.append([pr, sr, k])
        print(f"  {name:<25} {pr:>8.3f} {sr:>9.3f} {k:>7.3f}")

    print(f"{'=' * 80}")

    # =====================================================================
    # FIGURE 1: Scatter Plot with Regression Line
    # =====================================================================
    fig, ax = plt.subplots(figsize=(6, 5))
    ax.scatter(human_overall, llm_overall, alpha=0.7, edgecolors='k', s=60,
               color='#2196F3')

    # Perfect agreement line
    ax.plot([3, 9.5], [3, 9.5], 'r--', linewidth=1.5, label='Perfect Agreement')

    # Regression line
    m, b = np.polyfit(human_overall, llm_overall, 1)
    x_range = np.array([min(human_overall) - 0.5, max(human_overall) + 0.5])
    ax.plot(x_range, m * x_range + b, 'b-', linewidth=2,
            label=f'LLM Fit (r={pearson_r:.2f})')

    ax.set_xlabel("Human Examiner Band Score", fontsize=12)
    ax.set_ylabel("Gemini 2.5 Flash Band Score", fontsize=12)
    ax.set_title("Human vs. LLM Writing Scores", fontsize=14, fontweight='bold')
    ax.legend(fontsize=10)
    ax.set_xlim(3, 9.5)
    ax.set_ylim(3, 9.5)
    ax.set_aspect('equal')
    ax.grid(True, alpha=0.3)
    plt.tight_layout()
    plt.savefig(os.path.join(charts_dir, "human_vs_llm_scatter.png"), dpi=300)
    plt.close()
    print(f"\n  [OK] Saved: charts/human_vs_llm_scatter.png")

    # =====================================================================
    # FIGURE 2: Bland-Altman Agreement Plot
    # =====================================================================
    mean_scores = [(h + l) / 2 for h, l in zip(human_overall, llm_overall)]
    diff_scores = [l - h for h, l in zip(human_overall, llm_overall)]
    mean_diff = np.mean(diff_scores)
    std_diff = np.std(diff_scores)

    fig, ax = plt.subplots(figsize=(6, 5))
    ax.scatter(mean_scores, diff_scores, alpha=0.7, edgecolors='k', s=60,
               color='#4CAF50')
    ax.axhline(y=mean_diff, color='r', linestyle='-',
               label=f'Mean Diff ({mean_diff:+.2f})')
    ax.axhline(y=mean_diff + 1.96 * std_diff, color='gray', linestyle='--',
               label='+/-1.96 SD')
    ax.axhline(y=mean_diff - 1.96 * std_diff, color='gray', linestyle='--')
    ax.set_xlabel("Mean of Human and LLM Scores", fontsize=12)
    ax.set_ylabel("Difference (LLM - Human)", fontsize=12)
    ax.set_title("Bland-Altman Plot: Gemini vs Human Agreement",
                 fontsize=14, fontweight='bold')
    ax.legend(fontsize=10)
    ax.grid(True, alpha=0.3)
    plt.tight_layout()
    plt.savefig(os.path.join(charts_dir, "bland_altman_plot.png"), dpi=300)
    plt.close()
    print(f"  [OK] Saved: charts/bland_altman_plot.png")

    # =====================================================================
    # FIGURE 3: Per-Criterion Heatmap
    # =====================================================================
    metrics_names = ["Pearson r", "Spearman p", "Cohen's K"]
    df = pd.DataFrame(criterion_data, index=criteria_display, columns=metrics_names)

    fig, ax = plt.subplots(figsize=(6, 4))
    sns.heatmap(df, annot=True, fmt=".2f", cmap="RdYlGn", vmin=0, vmax=1,
                linewidths=0.5, ax=ax)
    ax.set_title("Per-Criterion Agreement: Gemini vs Human",
                 fontsize=14, fontweight='bold')
    plt.tight_layout()
    plt.savefig(os.path.join(charts_dir, "per_criterion_heatmap.png"), dpi=300)
    plt.close()
    print(f"  [OK] Saved: charts/per_criterion_heatmap.png")

    # =====================================================================
    # FIGURE 4: Error Distribution Histogram
    # =====================================================================
    fig, ax = plt.subplots(figsize=(6, 4))
    errors = [l - h for h, l in zip(human_overall, llm_overall)]
    bins = np.arange(-2.0, 2.25, 0.5)
    ax.hist(errors, bins=bins, color='#FF9800', edgecolor='black', alpha=0.8)
    ax.axvline(x=0, color='red', linestyle='--', linewidth=1.5, label='Zero error')
    ax.set_xlabel("Score Difference (LLM - Human)", fontsize=12)
    ax.set_ylabel("Number of Essays", fontsize=12)
    ax.set_title("Distribution of Grading Errors", fontsize=14, fontweight='bold')
    ax.legend()
    ax.grid(True, alpha=0.3, axis='y')
    plt.tight_layout()
    plt.savefig(os.path.join(charts_dir, "error_distribution.png"), dpi=300)
    plt.close()
    print(f"  [OK] Saved: charts/error_distribution.png")

    print(f"\n  All charts saved to: {charts_dir}")
    print("=" * 80)


if __name__ == "__main__":
    main()
