import { StyleSheet } from 'react-native';
import { SPACING, RADIUS, FONT_SIZES } from '@/constants';
import type { ThemeTokens } from '@/constants/theme';

export function createExerciseStyles(colors: ThemeTokens) {
  return StyleSheet.create({
    groupType: {
      fontSize: FONT_SIZES.md,
      fontWeight: '800',
      color: colors.text,
      textTransform: 'uppercase',
      letterSpacing: 1,
      marginBottom: SPACING.sm,
    },
    instructions: {
      backgroundColor: colors.surface,
      padding: SPACING.md,
      borderRadius: RADIUS.md,
      borderWidth: 1,
      borderColor: colors.border,
      marginBottom: SPACING.lg,
    },
    instructionsText: { fontSize: FONT_SIZES.sm, color: colors.textSecondary, lineHeight: 20 },
    qBlock: {
      backgroundColor: colors.card,
      borderRadius: RADIUS.xl,
      borderWidth: 1,
      borderColor: colors.border,
      padding: SPACING.lg,
      marginBottom: SPACING.md,
    },
    qNum: {
      fontSize: FONT_SIZES.xs,
      fontWeight: '700',
      color: colors.primary,
      textTransform: 'uppercase',
      marginBottom: 4,
    },
    qText: {
      fontSize: FONT_SIZES.md,
      color: colors.text,
      marginBottom: SPACING.md,
      lineHeight: 22,
    },
    option: {
      flexDirection: 'row',
      alignItems: 'center',
      gap: SPACING.md,
      padding: SPACING.md,
      borderRadius: RADIUS.lg,
      borderWidth: 1,
      marginBottom: SPACING.sm,
    },
    bullet: {
      width: 28,
      height: 28,
      borderRadius: 14,
      backgroundColor: colors.card,
      borderWidth: 1.5,
      borderColor: colors.border,
      alignItems: 'center',
      justifyContent: 'center',
      flexShrink: 0,
    },
    bulletLetter: { fontSize: FONT_SIZES.sm, fontWeight: '700', color: colors.textSecondary },
    optText: { flex: 1, fontSize: FONT_SIZES.sm, fontWeight: '600' },
    explanation: { marginTop: SPACING.sm, padding: SPACING.sm, borderRadius: RADIUS.md },
    input: {
      borderWidth: 1.5,
      borderColor: colors.border,
      borderRadius: RADIUS.md,
      padding: SPACING.md,
      fontSize: FONT_SIZES.md,
      color: colors.text,
    },

    qNumBadge: {
      minWidth: 24,
      height: 24,
      borderRadius: 4,
      borderWidth: 1,
      borderColor: '#BFDBFE',
      backgroundColor: '#EFF6FF',
      alignItems: 'center',
      justifyContent: 'center',
      paddingHorizontal: 4,
      marginTop: 2,
    },
    qNumBadgeText: { fontSize: 12, fontWeight: '700', color: '#1D4ED8' },

    tfngBtn: {
      paddingHorizontal: 16,
      paddingVertical: 10,
      borderRadius: RADIUS.md,
      borderWidth: 1,
    },
    tfngText: { fontSize: FONT_SIZES.sm, fontWeight: '700' },

    matchingOptionsBox: {
      backgroundColor: colors.surface,
      borderRadius: RADIUS.lg,
      borderWidth: 1,
      borderColor: colors.border,
      padding: SPACING.md,
      marginBottom: SPACING.md,
    },
    matchingOptionsTitle: {
      fontSize: 11,
      fontWeight: '800',
      color: colors.textMuted,
      textTransform: 'uppercase',
      marginBottom: 8,
    },
    matchingOptionRow: { flexDirection: 'row', gap: 8, marginBottom: 8, alignItems: 'center' },
    matchingOptionLetter: {
      width: 28,
      height: 28,
      borderRadius: 4,
      backgroundColor: colors.card,
      borderWidth: 1,
      borderColor: colors.border,
      alignItems: 'center',
      justifyContent: 'center',
    },
    matchingOptionLetterText: { fontSize: 13, fontWeight: '700', color: colors.text },
    matchingOptionText: { flex: 1, fontSize: 14, color: colors.text, fontWeight: '500' },

    matchingBtn: {
      width: 44,
      height: 44,
      borderRadius: 22,
      borderWidth: 1,
      alignItems: 'center',
      justifyContent: 'center',
    },
    matchingBtnText: { fontSize: FONT_SIZES.md, fontWeight: '700' },

    mcmOptionBtn: {
      flexDirection: 'row',
      alignItems: 'center',
      gap: 8,
      padding: SPACING.md,
      borderRadius: RADIUS.lg,
      borderWidth: 1,
      marginBottom: 8,
    },
    mcmCheckbox: {
      width: 20,
      height: 20,
      borderRadius: 4,
      borderWidth: 1.5,
      borderColor: colors.textMuted,
      alignItems: 'center',
      justifyContent: 'center',
    },
    mcmOptionText: { flex: 1, fontSize: FONT_SIZES.sm, lineHeight: 20 },
  });
}
